### ISSUE TITLE
rdslogs doesn't respect `AWS_DEFAULT_PROFILE` environment variable

### ISSUE THREAD

**Issue by gchpaco** [honeycombio/rdslogs#9] opened 2017-09-22 22:18 UTC
I have separate profiles, and as it happens for my configuration the default profile didn't have useful credentials.  I have the `AWS_DEFAULT_PROFILE` environment variable set normally, but that wasn't getting passed along when I ran `rdslogs`.

**Comment by garthk** [comment] 2018-05-10 23:57
Nor, `AWS_PROFILE`. The ~~strikeouts~~ in the README tell me it's a known problem, but this is the only issue I can find for it.

**Comment by garthk** [comment] 2018-05-11 01:16
6a878be on macOS 10.13.4:
```nil
$ export AWS_PROFILE=xxx
$ rdslogs --region ap-southeast-2 --dbtype=postgresql
Sending output to STDOUT
2018/05/11 11:00:57 Unable to locate credentials. You can configure credentials by running "aws configure".
```

`dtruss` shows opening `~/.aws/credentials`. I can't find a read, but it might be a red herring.

```nil
89391/0x1a7a351:  open("/Users/self/.aws/credentials\0", 0x1000000, 0x0)		 = 3 0
…
89391/0x1a7a351:  fcntl(0x3, 0x3, 0x0)		 = 0 0
89391/0x1a7a351:  fcntl(0x3, 0x4, 0x4)		 = 0 0
89391/0x1a7a351:  close(0x3)		 = 0 0
```

Perhaps I'm running into aws/aws-sdk-go#1019, which is a pity because its maintainers seem to have decided the mismatch between the Go SDK and other language SDKs is not a bug and, given the age, not urgent. Perhaps it's back-pressure from the combination of Go's dependency management challenges and the idea that [matching the other SDKs would be a breaking change][148812184], in particular for `AWS_DEFAULT_PROFILE`, which is tough luck for @gchpaco (see aws/aws-sdk-go#554).

[148812184]: https://github.com/aws/aws-sdk-go/issues/384#issuecomment-148812184

**Comment by MikeGoldsmith** [comment] 2021-09-08 14:59
We’re going to close this for now. Feel free to re-open if it’s still relevant.

**Closed by MikeGoldsmith** 2021-09-08 14:59 UTC
